### ISSUE TITLE
定義した関数に渡した引数が記憶される

### ISSUE THREAD

**Issue by TundraClimate** [KajizukaTaichi/idol#1]
![unknown](https://github.com/user-attachments/assets/4af48c67-0bbc-4bc0-a43a-fd4b782444b3)

.idファイル実行でも同様の動作  

仕様でしたらすみません

**Comment by KajizukaTaichi** [comment]
関数に引数長さチェック付けました。
https://github.com/KajizukaTaichi/idol/commit/254bf134365b11f7c703077b56f95d464606117e

ありがとうございます。
